In [1]:
import numpy as np

In [6]:
mat1 = np.array([[1,2], [3,4]])
mat1.shape

(2, 2)

Creating Matrix with Random values

In [9]:
mat2 = np.random.randint(1,50,20).reshape(5,4)
mat2

array([[40, 26, 23, 49],
       [31, 13, 42, 17],
       [ 5, 14,  2, 28],
       [27, 12, 47,  8],
       [ 5, 10, 13, 46]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.full((2,2), np.inf)

array([[inf, inf],
       [inf, inf]])

In [23]:
np.full((2,4), 'Nidhi')

array([['Nidhi', 'Nidhi', 'Nidhi', 'Nidhi'],
       ['Nidhi', 'Nidhi', 'Nidhi', 'Nidhi']], dtype='<U5')

Transpose

In [32]:
arr = np.random.randint(3,30,10).reshape(2,5)
arr

array([[23, 15,  6, 29, 27],
       [ 3,  8, 18, 23, 13]])

In [33]:
np.transpose(arr)

array([[23,  3],
       [15,  8],
       [ 6, 18],
       [29, 23],
       [27, 13]])

Matrix operations 

Addition

Element-wise 

condition - same number of elements (shape)

In [40]:
mat1 = np.random.randint(20, size = (5,4))
mat2 = np.random.randint(20, size = (5,4))
mat1 + mat2

array([[ 9, 11,  1, 30],
       [18,  8, 23, 27],
       [20, 25, 24, 27],
       [32, 18, 16,  6],
       [13,  5, 18, 30]])

In [42]:
np.add(mat1,mat2)

array([[ 9, 11,  1, 30],
       [18,  8, 23, 27],
       [20, 25, 24, 27],
       [32, 18, 16,  6],
       [13,  5, 18, 30]])

In [43]:
mat1 = np.random.randint(20, size = (4,5))
mat2 = np.random.randint(20, size = (5,4))
mat1 + mat2

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

Subtraction 

In [44]:
mat1 = np.random.randint(20, size = (5,4))
mat2 = np.random.randint(20, size = (5,4))
mat1 - mat2

array([[  2,  -1,  -4, -10],
       [ -1,  13, -11,   8],
       [  8,   7,   5,  -2],
       [ -5,  18,   5,  13],
       [ -6, -11,   5,   0]])

In [48]:
np.subtract(mat1,mat2)

array([[  2,  -1,  -4, -10],
       [ -1,  13, -11,   8],
       [  8,   7,   5,  -2],
       [ -5,  18,   5,  13],
       [ -6, -11,   5,   0]])

In [49]:
mat1 = np.random.randint(20, size = (4,5))
mat2 = np.random.randint(20, size = (5,4))
mat1 - mat2

ValueError: operands could not be broadcast together with shapes (4,5) (5,4) 

Multiplication 

1. scalar to vector> np.multiply (element by element)

2. Vector to vector > condition > number of columns in first v = number of rows in second v

In [50]:
a = 2
b = np.random.randint(20, size = (2,3))
a*b

array([[12, 32, 32],
       [12,  2, 30]])

In [51]:
np.multiply(a,b)

array([[12, 32, 32],
       [12,  2, 30]])

In [58]:
a = np.random.randint(20,size = (3,3))
b = np.random.randint(20, size = (3,4))
a*b
#a*b will give element by element 

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [59]:
np.dot(a,b)

array([[359, 385, 180, 364],
       [163, 357, 158, 292],
       [194, 266, 111, 260]])