Advanatges of Numpy :
    1. Allows several Mathematical operations
    2. Faster operations

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
type(arr)

In [ ]:
np.arange(10).reshape(2,5)

In [ ]:
my_list = [i for i in range(10) if i%2 ==0] #list comprehensions
my_list

In [11]:
#checking shape
arr.shape

(4,)

In [13]:
arr.reshape(2,2) #changing the shape

array([[1, 2],
       [3, 4]])

In [20]:
np.array(list(range(10)), dtype = float).reshape(2,5)

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Initial Placeholder in arrays

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
np.full((2,4),'Nidhi') #fillvalue #value

array([['Nidhi', 'Nidhi', 'Nidhi', 'Nidhi'],
       ['Nidhi', 'Nidhi', 'Nidhi', 'Nidhi']], dtype='<U5')

In [38]:
np.identity(3) #identity matrix #rows = #columns

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [43]:
np.random.rand(6)

array([0.53501607, 0.00716757, 0.93259672, 0.60638233, 0.61724321,
       0.01646486])

In [44]:
np.random.normal(7)

7.084868488715988

In [45]:
np.random.randn(9)

array([-0.81248022,  1.20983154, -0.33539029, -0.48552608,  0.70287124,
       -1.59785761, -0.21051723,  0.13075022,  0.45493163])

In [48]:
np.random.random((5,2)) #distributed over [0,1]

array([[0.0415635 , 0.92339402],
       [0.58069216, 0.54582275],
       [0.61492357, 0.76506858],
       [0.90286332, 0.10992667],
       [0.95069086, 0.75557789]])

In [53]:
np.random.randint(10,1000,6).reshape(2,3) #random integers
np.random.randint(10,1000,(2,3))

array([[506, 527, 627],
       [325, 186, 306]])

In [59]:
#array of evenly spaced values
np.linspace(10,30,20) #specify the number of values required

array([10.        , 11.05263158, 12.10526316, 13.15789474, 14.21052632,
       15.26315789, 16.31578947, 17.36842105, 18.42105263, 19.47368421,
       20.52631579, 21.57894737, 22.63157895, 23.68421053, 24.73684211,
       25.78947368, 26.84210526, 27.89473684, 28.94736842, 30.        ])

In [62]:
np.arange(10,30,5) #number of steps 

array([10, 15, 20, 25])

In [64]:
arr = np.random.randint(10,90,(5,5))
arr

array([[20, 27, 65, 47, 37],
       [40, 71, 50, 80, 85],
       [10, 33, 47, 15, 39],
       [84, 82, 12, 80, 82],
       [42, 11, 33, 35, 23]])

In [65]:
arr.size

25

In [66]:
arr.ndim

2

Indexing and Slicing

In [67]:
arr[2:3,2:4]

array([[47, 15]])

In [70]:
arr[3:5,]

array([[84, 82, 12, 80, 82],
       [42, 11, 33, 35, 23]])

In [71]:
arr[:,3:]

array([[47, 37],
       [80, 85],
       [15, 39],
       [80, 82],
       [35, 23]])

In [73]:
arr.dtype

dtype('int32')

Mathematical operations in Numpy

In [77]:
list1 = list(range(10))
list2 = list(range(10))

print(list1 + list2) #addition of list concatenate them not do element by element operation

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [79]:
a = np.random.randint(10,90,(3,3))
b = np.random.randint(20,100,(3,3))

print(a+b) #numpy helps to do element by element operation
print(a-b)
print(a*b)
print(a/b)

[[129  94 121]
 [114 107  65]
 [100 106  43]]
[[  7 -18  15]
 [  4 -57 -39]
 [ 24  44  -7]]
[[4148 2128 3604]
 [3245 2050  676]
 [2356 2325  450]]
[[1.1147541  0.67857143 1.28301887]
 [1.07272727 0.30487805 0.25      ]
 [1.63157895 2.41935484 0.72      ]]


In [81]:
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)

array([[1.1147541 , 0.67857143, 1.28301887],
       [1.07272727, 0.30487805, 0.25      ],
       [1.63157895, 2.41935484, 0.72      ]])

Array Manipulation

In [82]:
arr = np.random.randint(1,10,(2,5))
arr

array([[4, 1, 8, 6, 2],
       [7, 8, 8, 3, 6]])

In [83]:
np.transpose(arr)

array([[4, 7],
       [1, 8],
       [8, 8],
       [6, 3],
       [2, 6]])

In [84]:
arr.T

array([[4, 7],
       [1, 8],
       [8, 8],
       [6, 3],
       [2, 6]])

In [88]:
np.where(arr>5,'yes','No')

array([['No', 'No', 'yes', 'yes', 'No'],
       ['yes', 'yes', 'yes', 'No', 'yes']], dtype='<U3')

In [90]:
np.where(arr==6) #if no condition is specified it just gives the index where cond is true

(array([0, 1], dtype=int64), array([3, 4], dtype=int64))

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
i = [4,5,6,710,0]

np.where(i>'6', 'yes', 'no')

TypeError: '>' not supported between instances of 'list' and 'str'

In [19]:
arr = np.arange(10)
np.where(arr>6, 'yes', 'no')

array(['no', 'no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes'],
      dtype='<U3')

In [20]:
np.random.randint(7)

4

In [21]:
np.random.rand(8)

array([0.72257124, 0.87059897, 0.93770572, 0.64092906, 0.40369364,
       0.45855416, 0.99560686, 0.85382101])

In [23]:
arr = np.array([3,4,4])

np.where(arr>3, 'yes', 'no')

array(['no', 'yes', 'yes'], dtype='<U3')

In [5]:
arr = np.array(list(range(10)))

In [7]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
arr[arr>5]

array([6, 7, 8, 9])

In [10]:
np.where(arr>5, 'yes', 'no')

array(['no', 'no', 'no', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes'],
      dtype='<U3')

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.random.random(7)

array([0.59058182, 0.40524046, 0.45611964, 0.70915499, 0.75367962,
       0.14853061, 0.78168251])

In [20]:
np.random.rand(7)

array([0.73703846, 0.90378705, 0.04316366, 0.65031917, 0.69812644,
       0.93780142, 0.75502959])

In [24]:
np.random.randint(0,90,4)  #start end and len

array([83, 11,  9,  6])

In [ ]:
np.random.